%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/giuseppe/Google Drive/-DENI-/Varie/Salute/Coronavirus/coronavirus m_files 2/dpc-covid19-ita-andamento-nazionale.csv
%
% Auto-generated by MATLAB on 12-Mar-2021 12:07:52

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 24);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["data", "stato", "ricoverati_con_sintomi", "terapia_intensiva", "totale_ospedalizzati", "isolamento_domiciliare", "totale_positivi", "variazione_totale_positivi", "nuovi_positivi", "dimessi_guariti", "deceduti", "casi_da_sospetto_diagnostico", "casi_da_screening", "totale_casi", "tamponi", "casi_testati", "note", "ingressi_terapia_intensiva", "note_test", "note_casi", "totale_positivi_test_molecolare", "totale_positivi_test_antigenico_rapido", "tamponi_test_molecolare", "tamponi_test_antigenico_rapido"];
opts.VariableTypes = ["string", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["data", "ingressi_terapia_intensiva", "note_test", "note_casi", "totale_positivi_test_molecolare", "totale_positivi_test_antigenico_rapido", "tamponi_test_molecolare", "tamponi_test_antigenico_rapido"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["data", "stato", "ingressi_terapia_intensiva", "note_test", "note_casi", "totale_positivi_test_molecolare", "totale_positivi_test_antigenico_rapido", "tamponi_test_molecolare", "tamponi_test_antigenico_rapido"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "note", "TrimNonNumeric", true);
opts = setvaropts(opts, "note", "ThousandsSeparator", ",");

% Import the data
itanaz = readtable("/Users/giuseppe/Google Drive/-DENI-/Varie/Salute/Coronavirus/coronavirus m_files 2/dpc-covid19-ita-andamento-nazionale.csv", opts);


%% Clear temporary variables
clear opts